bots/urls.py
from django.conf.urls import url

from . import views
app_name = 'bots'
urlpatterns = [
    url(r'^$', views.index, name='index-calc'),
    url(r'^consulta/$', views.consulta_datos_servicio, name='consulta'),
    url(r'^resultados/$', views.resultados, name='resultados'),
    url(r'^calculadora/$', views.Calculadora.as_view(), name='calculadora'),
    url(r'^procesar/$', views.procesar_opcion, name='procesar'),
    url(r'^plan-express/$', views.ProcesarPlanView.as_view(), name='plan-express'),
    url(r'^plan-moderado/$', views.ProcesarPlanView.as_view(), name='plan-moderado'),
    url(r'^plan-largo-plazo/$', views.ProcesarPlanView.as_view(), name='plan-lp'),
    url(r'^tu-cotizacion/$', views.TuCotizacion.as_view(), name='tu-cotizacion'),
]

clientes/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views
app_name = 'clientes'
urlpatterns = [

    url(r'^acceso/$', login, {'template_name': 'clientes/login.html'}, name='acceso'),
    url(r'^adios/$', logout, {'template_name': 'clientes/logout.html'}, name='adios'),
    url(r'^registro/$', views.registro, name='registro'),
    url(r'^perfil/$', views.perfil, name='perfil'),
    url(r'^perfil/editar/$', views.editar_perfil, name='editar_perfil'),
    url(r'^cambiar-contrasena/$', views.cambiar_password, name='cambiar_contrasena'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^autorizar-consulta-sic/$', views.autorizar_consulta_sic, name='autorizar-consulta-sic'),
    url(r'^gracias/$', views.gracias, name='gracias'),
    url(r'^ajax_send_pin/$', views.ajax_send_pin, name='send_pin'),
]

ecoluz/urls.py
# -*- coding: utf-8 -*-
"""ecoluz URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from ecoluzweb import views
from django.conf import settings
from django.conf.urls.static import static
from . import views as vw
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)


urlpatterns = [
    url(r'^eco-v1/', admin.site.urls),
    url(r'^$', views.inicio, name='inicio'),
    url(r'^clientes/', include('clientes.urls')),
    url(r'^usuarios/', include('usuarios.urls'), name='usuarios'),
    url(r'^ecoclientes/', include('ecoclientes.urls'), name='ecoclientes'),
    url(r'^conoce-tu-ahorro/', include('bots.urls'), name='conoce-tu-ahorro'),
    url(r'^proyectos/', views.proyectos, name='proyectos'),
    url(r'^que-es-ecoluz/', views.que_es_ecoluz, name='que-es-ecoluz'),
    url(r'^terminos-y-condiciones', views.terminos_y_condiciones, name='terminos-y-condiciones'),
    url(r'^aviso-de-privacidad', views.aviso_de_privacidad, name='aviso-de-privacidad'),
    url(r'^contacto', views.contacto, name='contacto'),
    url(r'^ingresando', vw.wherenext, name='ingresando'),

    url('^reestablecer-contrasena/$', auth_views.password_reset,
        {
            'template_name': 'clientes/password_reset_form.html',
            'html_email_template_name': 'clientes/password_reset_email.html',
        }, name='password_reset'),
    url(r'^reestablecer-contrasena/listo/$',
        PasswordResetDoneView.as_view(template_name='clientes/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reestablecer-contrasena/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='clientes/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reestablecer-contrasena/hecho/$',
        PasswordResetCompleteView.as_view(template_name='clientes/password_reset_complete.html'),
        name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext as _


# Create your models here.
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'clientes/user_{0}/{1}'.format(instance.id, filename)


class UserManager(BaseUserManager):
    """Define a model manager for Cliente model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a Cliente with the given email and password."""
        if not email:
            raise ValueError('Correo electrónico obligatorio')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular Cliente with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class Cliente(AbstractUser):
    ESTATUS_FINANCIAMIENTO = (

        ('APROBADO', 'APROBADO'),
        ('RECHAZADO', 'RECHAZADO'),
        ('VALIDANDO', 'VALIDANDO'),
        ('PENDIENTE', 'PENDIENTE'),
    )
    ESTADO_CIVIL = (

        ('SOLTERA/O', 'SOLTERA/O'),
        ('CASADA/O', 'CASADA/O'),
    )
    REGIMEN = (
        ('NO APLICA', 'NO APLICA'),
        ('SEPARACIÓN DE BIENES', 'SEPARACIÓN DE BIENES'),
        ('SOCIEDAD CONYUGAL', 'SOCIEDAD CONYUGAL'),
    )


    # Datos del cliente
    username = None
    email = models.EmailField('Correo electrónico', unique=True)
    foto_file = models.FileField(_('Foto del cliente'), upload_to=user_directory_path, blank=True)
    telefono = models.CharField(_('Teléfono'), max_length=10, blank=True)
    calle = models.CharField(_('Calle'), max_length=50, blank=True)
    numero_exterior = models.CharField(_('Número exterior'), max_length=10, blank=True)
    numero_interior = models.CharField(_('Número interior'), max_length=10, blank=True)
    colonia = models.CharField(_('Colonia'), max_length=50, blank=True)
    delegacion_municipio = models.CharField(_('Delegación o Municipio'), max_length=50, blank=True)
    ciudad = models.CharField(_('Ciudad'), max_length=50, blank=True)
    estado = models.CharField(_('Estado'), max_length=50, blank=True)
    codigo_postal = models.IntegerField(_('Código postal'), blank=True, default=0)
    estado_civil = models.CharField(_('Estado civil'), max_length=10, choices=ESTADO_CIVIL, blank=True)
    regimen_conyugal = models.CharField(_('Régimen conyugal'), max_length=20, choices=REGIMEN, blank=True)
    rfc = models.CharField(_('RFC'), max_length=20, blank=True)
    razon_social = models.CharField(_('Razón social'), max_length =50, blank=True)
    domicilio_fiscal = models.CharField(_('Domicilio fiscal'), max_length=50, blank=True)
    curp = models.CharField(_('CURP'), max_length=30, blank=True)
    # Documentos del cliente
    identificacion_file = models.FileField(_('Identificación (INE ambos lados/Pasaporte)'), upload_to=user_directory_path, blank=True)
    curp_file = models.FileField(_('Cédula CURP'), upload_to=user_directory_path, blank=True)
    cedula_rfc_file = models.FileField(_('Cédula RFC'), upload_to=user_directory_path, blank=True)
    recibo_luz_file = models.FileField(_('Recibo de luz'), upload_to=user_directory_path, blank=True)
    comprobante_ingresos_file = models.FileField(_('Comprobante de ingresos (último año)'), upload_to=user_directory_path, blank=True)
    comprobante_domicilio = models.FileField(_('Comprobante de domicilio'), upload_to=user_directory_path, blank=True)
    # Datos y documentos del obligado solidario
    obligado_nombre = models.CharField(_('Nombre'), max_length=20, blank=True)
    obligado_apellido = models.CharField(_('Apellido'), max_length=20, blank=True)
    obligado_relacion = models.CharField(_('Relación'), max_length=20, blank=True)
    obligado_rfc = models.CharField(_('RFC'), max_length=20, blank=True)
    obligado_curp = models.CharField(_('CURP'), max_length=30, blank=True)
    obligado_identificacion_file = models.FileField(_('Identificación (INE ambos lados/Pasaporte)'), upload_to=user_directory_path, blank=True)
    obligado_rfc_file = models.FileField(_('Cédula RFC'), upload_to=user_directory_path, blank=True)
    obligado_curp_file = models.FileField(_('Cédula CURP'), upload_to=user_directory_path, blank=True)
    obligado_recibo_luz = models.FileField(_('Recibo de luz'), upload_to=user_directory_path, blank=True)
    obligado_comprobante_domicilio = models.FileField(_('Comprobante de domicilio'), upload_to=user_directory_path, blank=True)
    #Datos del plan de finaciamiento
    plan_elegido = models.CharField(_('Plan de financiamiento elegido'), max_length=20, blank=True)
    monto_credito = models.CharField(_('Monto del crédito'), max_length=20, blank=True)
    numero_de_paneles = models.CharField(_('Cantidad de paneles'), max_length=10, blank=True)
    enganche = models.CharField(_('Enganche'), max_length=20, blank=True)
    numero_de_pagos = models.CharField(_('Cantidad de pagos'), max_length=5, blank=True)
    pago_mensual = models.CharField(_('Pago mensual'), max_length=20, blank=True)
    estado_del_financiamiento = models.CharField(_('Estatus del financiamiento'), max_length=9, choices=ESTATUS_FINANCIAMIENTO, default='PENDIENTE')
    consumo_kw_promedio = models.CharField(_('Consumo promedio Kw'), max_length=20, blank=True)
    importe_promedio_cfe = models.CharField(_('Importe promedio CFE'), max_length=20, blank=True)
    terms = models.BooleanField(_('Acepto los términos y condiciones'),
        error_messages={'required': 'Debes aceptar los términos y condiciones'}, blank=True, default=False
    )
    #Campos de verificación de cuenta, perfil completo y autorización de consulta en buró de crédito
    mail_confirmed = models.BooleanField(_('Correo electrónico confirmado'), blank=True, default=False)
    perfil_completo = models.BooleanField(_('Información de perfil completa'), blank=True, default=False)
    autorizacion_buro_credito = models.BooleanField(_('Autorizo a Eco Luz a consultar mi información crediticia'), error_messages={'required': 'Debes marcar esta casilla para poder continuar'}, blank=True, default=False)
    fecha_autorizacion_de_consulta = models.DateField(_('Fecha de autorización de consulta de información crediticia'), blank=True, null=True)
    hora_autorizacion_de_consulta = models.TimeField(_('Hora de autorización de consulta de información creditica'), blank=True, null=True)
    fecha_de_consulta_buro = models.DateField(_('Fecha de consulta de información crediticia'), blank=True, null=True)
    hora_de_consulta_buro = models.TimeField(_('Hora de consulta de información crediticia'), blank=True, null=True)
    tipo_usuario = models.CharField(_('tipo usuario'), max_length=12, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

clientes/templates/clientes/autorizacion_consulta_sic.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}Autorización para consultar tu información crediticia{% endblock %}

    {% block content %}
     <div class="container">
        <div class="row">
            <div class="col-sm-12" style="margin-top: 100px">
                    <div class="col-sm-12" style="background-color: #e5e5e5;">
                        <br>
                            <div class="form-group">
                                <div class="row">
                                <div class="col-md-4">
                                    <div class="row">
                                    <p><a class="btn btn-primary col-md-8 col-md-offset-2" style="color: #fff !important;" href="{% url 'clientes:perfil' %}"><span>VER MI PERFIL</span></a></p>
                                    </div>
                                    <br>
                                    <div class="row">
                                    <p><a class="btn btn-primary col-md-8 col-md-offset-2" style="color: #fff !important;" href="{% url 'clientes:editar_perfil' %}">EDITAR INFORMACIÓN DE MI PERFIL</a></p>
                                    </div>
                                    <br>
                                    <div class="row">
                                    <p><a class="btn btn-primary col-md-8 col-md-offset-2" style="color: #fff !important;" href="{% url 'clientes:cambiar_contrasena' %}">CAMBIAR CONTRASEÑA</a></p>
                                    </div>
                                    <br>
                                    <div class="row">
                                    <p><a class="btn btn-warning col-md-8 col-md-offset-2" style="color: #fff !important;" href="{% url 'clientes:adios' %}">SALIR</a></p>
                                    </div>
                                </div>

                                <div class="col-md-7 ">
                                    {% if messages %}
                                            <div class="row">
                                            <div class="col-md-2"></div>
                                            <div class="alert alert-info col-md-8 alert-dismissable">
                                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                                {% for message in messages %}
                                                    {{ message }}
                                                {% endfor %}
                                            </div>
                                            <div class="col-md-2"></div>
                                            </div>
                                    {% endif %}
                                    <h3>AUTORIZACIÓN PARA CONSULTAR TU INFORMACIÓN CREDITICIA</h3>
                                    <br>
                                    <div class="col-sm-offset-1 col-sm-10" style="background-color: #e5e5e5;">
                                    <br>
                                    <p class="text-justify"> Por este medio, declaro bajo protesta de decir verdad que la información proporcionada a
                                        <strong class="strong-green">Ecological Crowd Operations S.A.P.I. de C.V.</strong> en este formato electrónico
                                        es verdadera y precisa y por este medio libero a <strong class="strong-green">Ecological Crowd Operations S.A.P.I. de C.V.</strong>
                                        de cualquier responsabilidad de la misma.
                                        <br>
                                        <br>Por este medio autorizo expresamente a <strong class="strong-green">Ecological Crowd Operations S.A.P.I. de C.V.</strong>,
                                        para que por conducto de sus funcionarios facultados lleve a cabo investigaciones sobre mi comportamiento crediticio o el de la Empresa
                                        que represento en la Sociedad de Información Crediticia que estime conveniente.
                                        <br>
                                        <br>Asimismo, declaro que conozco la naturaleza y alcance de la información que se solicitará, del uso que
                                            <strong class="strong-green">Ecological Crowd Operations S.A.P.I. de C.V.</strong> hará de tal información y que podrá realizar
                                            consultas periódicas sobre mi historial o el de la empresa que represento, consintiendo que esta
                                            autorización se encuentre vigente por un período de 3 años contados a partir de su expedición y en todo
                                            caso durante el tiempo que se mantenga la relación jurídica.
                                        <br>
                                        <br> En caso de que la solicitante sea una Persona Moral, declaro bajo protesta de decir verdad Ser
                                             Representante Legal de la empresa mencionada en esta autorización; manifestando que a la fecha de
                                             firma de la presente autorización los poderes no me han sido revocados, limitados, ni modificados en
                                             forma alguna.
                                        <br>
                                        <br> Estoy de acuerdo y acepto que este documento quede bajo propiedad de <strong class="strong-green">Ecological Crowd Operations S.A.P.I. de C.V.</strong>
                                             y/o Sociedad de Información Crediticia consultada para efectos de control y cumplimiento
                                             del artículo 28 de la Ley para Regular a Las Sociedades de Información Crediticia; mismo que señala
                                             que las Sociedades sólo podrán proporcionar información a un Usuario, cuando éste cuente con la
                                             autorización expresa del Cliente mediante su firma autógrafa
                                    <br> </div>

                                    <div class="container">
                                        <div class="form-group">
                                        <form id="auth" method="post">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-lg-10">{{ form.autorizar_consulta_sic }}<label class="control-label" style="padding-left: 1%;">Estoy de acuerdo y doy mi autorización.</label></div>
                                            </div>
                                            <div class="col-sm-6" style="background-color: #e5e5e5;">
                                                <p class="text-justify">

                                                    <br>A continuación te enviaremos a tu celular un mensaje con un NIP que servirá como firma digital para la presente autorización. Escribe el NIP que recibas y a continuación pulsa el botón FINALIZAR.
                                                <br> </div>
                                            <div class="row">
                                                <div class="col-lg-10">{{ form.numero_cel }}<button class="btn btn-primary" type="button" onClick="send_pin()" style="margin-left: 1%;">Obtener NIP</button></div>
                                            </div>
                                            <div class="row">
                                                <br>
                                                <div class="col-lg-10"><label class="control-label" style="padding-right: 1%;">NIP recibido:</label>{{ form.pin }}</div>
                                                <br>
                                                <br>
                                                <div class="col-lg-4 col-lg-offset-2"><input type="submit" class="btn btn-success" id="autorizacion_button" value="FINALIZAR" /></div>
                                            </div>
                                        </form>
                                        </div>
                                    </div>

                                </div>
                                </div>
                            <!--</div>-->
                        <br> </div>
                    <br> </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br> </div>

    {% endblock %}
    <!-- End container -->
    <!-- Start footer -->
    {% block footer %}
    {% include 'footer/_footer-sections.html' %}
    {% endblock %}
    <!-- End footer -->
    {% block js-special %}
    <!--<script type="text/javascript" src="{% static 'clientes/js/spin.js' %}"></script>-->
    <script>
    function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    function send_pin() {
    var prefix = "+521"
    $.ajax({
                url: "{% url 'clientes:send_pin' %}",
                type: "POST",
                data: { mobile_number: prefix + $("#id_numero_cel").val(), authorized: "True" },
            })
            .done(function(data) {
                alert("Se ha enviado el NIP de verificación Eco Luz a tu celular");
            })
            .fail(function(jqXHR, textStatus, errorThrown) {
                alert(errorThrown + ' : ' + jqXHR.responseText);
            });
    }
    </script>
    <script>

        var input = document.getElementById('id_autorizar_consulta_sic');
        input.oninvalid = function(event) {
            event.target.setCustomValidity('Debe marcar esta casilla para autorizar y poder continuar.');
        }

    </script>
    {% endblock %}

clientes/templates/clientes/confirmacion-correo-error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>El enlace de confirmación de correo es inválido</h2>
</body>
</html>

clientes/templates/clientes/confirmar-correo.html
{% autoescape off %}
Bienvenido a Ecoluz, {{ user.first_name }},
<br>
<br>
Por favor, haz click en el siguiente enlace para que podamos confirmar tu dirección de correo electrónico:
<br>
http://{{ domain }}{% url 'clientes:activate' uidb64=uid token=token %}
{% endautoescape %}

clientes/templates/clientes/edit_profile.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}Editar perfil{% endblock %}

    {% block content %}
     <div class="container">
        <div class="row">
            <div class="col-sm-12" style="margin-top: 100px">
                    <div class="col-sm-12" style="background-color: #e5e5e5;">
                        <br>
                            <div class="form-group">
                                <div class="row">
                                <div class="col-md-4">
                                    <div class="row">
                                    <p><a class="btn btn-primary col-md-8 col-md-offset-2" style="color: #fff !important;" href="{% url 'clientes:perfil' %}"><span>VER MI PERFIL</span></a></p>
                                    </div>
                                    <br>
                                    <div class="row">
                                    <p><a class="btn btn-primary col-md-8 col-md-offset-2" style="color: #fff !important;" href="{% url 'clientes:editar_perfil' %}">EDITAR INFORMACIÓN DE MI PERFIL</a></p>
                                    </div>
                                    <br>
                                    <div class="row">
                                    <p><a class="btn btn-primary col-md-8 col-md-offset-2" style="color: #fff !important;" href="{% url 'clientes:cambiar_contrasena' %}">CAMBIAR CONTRASEÑA</a></p>
                                    </div>
                                    <br>
                                    <div class="row">
                                    <p><a class="btn btn-warning col-md-8 col-md-offset-2" style="color: #fff !important;" href="{% url 'clientes:adios' %}">SALIR</a></p>
                                    </div>
                                </div>

                                <div class="col-md-7 ">
                                    <h3>EDITANDO PERFIL</h3>
                                    <br>
                                    <p>En esta página podrás llenar la información requerida para continuar con tu financiamiento <strong class="strong-green">Eco Luz</strong>. Antes de guardar la información, verifica que ésta sea correcta y que hayas subido los documentos requeridos.</p>
                                    <br>
                                    <form id="profile" method="post" enctype="multipart/form-data">

                                    {% crispy cliente_form %}
                                    <!--<p><input type="button" class="btn btn-flat btn-success" id="next_button" value="SIGUIENTE" style="display:block;"/><input type="button" class="btn btn-flat btn-success" id="prev_button" value="ANTERIOR" style="display:none;"/></p>-->
                                        <button type="submit" class="btn btn-flat btn-primary">GUARDAR CAMBIOS</button>
                                </form>
                                </div>
                                </div>
                            </div>
                        <br> </div>
                    <br> </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br> </div>

    {% endblock %}
    <!-- End container -->
    <!-- Start footer -->
    {% block footer %}
    {% include 'footer/_footer-sections.html' %}
    {% endblock %}
    <!-- End footer -->
    {% block js-special %}
    <script src="{% static 'clientes/js/validation.js' %}"></script>
    <script src="{% static 'clientes/js/tabnav.js' %}"></script>
    {% endblock %}

clientes/templates/clientes/gracias.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}¡Gracias!{% endblock %}

    {% block content %}
     <div class="container">
        <div class="row">
            <div class="col-sm-12" style="margin-top: 100px">
                    <div class="col-sm-12" style="background-color: #e5e5e5;">
                        <br>
                            <div class="form-group">
                                <div class="row">
                                <div class="col-md-4">
                                    <div class="row">
                                    <p><a class="btn btn-primary col-md-8 col-md-offset-2" style="color: #fff !important;" href="{% url 'clientes:perfil' %}"><span>VER MI PERFIL</span></a></p>
                                    </div>
                                    <br>
                                    <div class="row">
                                    <p><a class="btn btn-primary col-md-8 col-md-offset-2" style="color: #fff !important;" href="{% url 'clientes:editar_perfil' %}">EDITAR INFORMACIÓN DE MI PERFIL</a></p>
                                    </div>
                                    <br>
                                    <div class="row">
                                    <p><a class="btn btn-primary col-md-8 col-md-offset-2" style="color: #fff !important;" href="{% url 'clientes:cambiar_contrasena' %}">CAMBIAR CONTRASEÑA</a></p>
                                    </div>
                                    <br>
                                    <div class="row">
                                    <p><a class="btn btn-warning col-md-8 col-md-offset-2" style="color: #fff !important;" href="{% url 'clientes:adios' %}">SALIR</a></p>
                                    </div>
                                </div>

                                <div class="col-md-7 ">
                                    <h3>Gracias por completar la información. En los próximos días nos pondremos en contacto contigo para darte una respuesta. :)</h3>
                                    <br>
                                    <br>
                                    <h3>Atentamente <strong class="strong-green">Eco Luz</strong> </h3>
                                </div>
                                </div>
                            </div>
                        <br> </div>
                    <br> </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br> </div>

    {% endblock %}
    <!-- End container -->
    <!-- Start footer -->
    {% block footer %}
    {% include 'footer/_footer-sections.html' %}
    {% endblock %}
    <!-- End footer -->
    {% block js-special %}

    {% endblock %}

clientes/templates/clientes/password_reset_complete.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block head_title %}Contraseña actualizada{% endblock %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col-sm-12" style="margin-top: 100px">
                    <div class="col-sm-12" style="background-color: #e5e5e5;">
                        <br>
                            <div class="form-group">
                                <div class="row">
                                <div class="col-md-7 ">

<p>Su contraseña ha sido actualizada. Ahora puede iniciar sesión en su cuenta usando su nueva contraseña.</p>

<p><a class="btn btn-flat btn-primary" href="{% url 'clientes:acceso' %}" style="color: #fff !important;">INICIAR SESIÓN</a></p>
 </div>
                                </div>
                            </div>
                        <br> </div>
                    <br> </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br> </div>
{% endblock %}
<!-- Start footer -->
    {% block footer %}
    {% include 'footer/_footer-sections.html' %}
    {% endblock %}
    <!-- End footer -->
    {% block js-special %}

    {% endblock %}