bots/urls.py
from django.conf.urls import url

from . import views
app_name = 'bots'
urlpatterns = [
    url(r'^$', views.index, name='index-calc'),
    url(r'^consulta/$', views.consulta_datos_servicio, name='consulta'),
    url(r'^resultados/$', views.resultados, name='resultados'),
    url(r'^calculadora/$', views.Calculadora.as_view(), name='calculadora'),
    url(r'^procesar/$', views.procesar_opcion, name='procesar'),
    url(r'^plan-express/$', views.ProcesarPlanView.as_view(), name='plan-express'),
    url(r'^plan-moderado/$', views.ProcesarPlanView.as_view(), name='plan-moderado'),
    url(r'^plan-largo-plazo/$', views.ProcesarPlanView.as_view(), name='plan-lp'),
    url(r'^tu-cotizacion/$', views.TuCotizacion.as_view(), name='tu-cotizacion'),
]

clientes/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views
app_name = 'clientes'
urlpatterns = [

    url(r'^acceso/$', login, {'template_name': 'clientes/login.html'}, name='acceso'),
    url(r'^adios/$', logout, {'template_name': 'clientes/logout.html'}, name='adios'),
    url(r'^registro/$', views.registro, name='registro'),
    url(r'^perfil/$', views.perfil, name='perfil'),
    url(r'^perfil/editar/$', views.editar_perfil, name='editar_perfil'),
    url(r'^cambiar-contrasena/$', views.cambiar_password, name='cambiar_contrasena'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^autorizar-consulta-sic/$', views.autorizar_consulta_sic, name='autorizar-consulta-sic'),
    url(r'^gracias/$', views.gracias, name='gracias'),
    url(r'^ajax_send_pin/$', views.ajax_send_pin, name='send_pin'),
]

ecoluz/urls.py
# -*- coding: utf-8 -*-
"""ecoluz URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from ecoluzweb import views
from django.conf import settings
from django.conf.urls.static import static
from . import views as vw
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)


urlpatterns = [
    url(r'^eco-v1/', admin.site.urls),
    url(r'^$', views.inicio, name='inicio'),
    url(r'^clientes/', include('clientes.urls')),
    url(r'^usuarios/', include('usuarios.urls'), name='usuarios'),
    url(r'^ecoclientes/', include('ecoclientes.urls'), name='ecoclientes'),
    url(r'^conoce-tu-ahorro/', include('bots.urls'), name='conoce-tu-ahorro'),
    url(r'^proyectos/', views.proyectos, name='proyectos'),
    url(r'^que-es-ecoluz/', views.que_es_ecoluz, name='que-es-ecoluz'),
    url(r'^terminos-y-condiciones', views.terminos_y_condiciones, name='terminos-y-condiciones'),
    url(r'^aviso-de-privacidad', views.aviso_de_privacidad, name='aviso-de-privacidad'),
    url(r'^contacto', views.contacto, name='contacto'),
    url(r'^ingresando', vw.wherenext, name='ingresando'),

    url('^reestablecer-contrasena/$', auth_views.password_reset,
        {
            'template_name': 'clientes/password_reset_form.html',
            'html_email_template_name': 'clientes/password_reset_email.html',
        }, name='password_reset'),
    url(r'^reestablecer-contrasena/listo/$',
        PasswordResetDoneView.as_view(template_name='clientes/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reestablecer-contrasena/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='clientes/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reestablecer-contrasena/hecho/$',
        PasswordResetCompleteView.as_view(template_name='clientes/password_reset_complete.html'),
        name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext as _


# Create your models here.
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'clientes/user_{0}/{1}'.format(instance.id, filename)


class UserManager(BaseUserManager):
    """Define a model manager for Cliente model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a Cliente with the given email and password."""
        if not email:
            raise ValueError('Correo electrónico obligatorio')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular Cliente with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class Cliente(AbstractUser):
    ESTATUS_FINANCIAMIENTO = (

        ('APROBADO', 'APROBADO'),
        ('RECHAZADO', 'RECHAZADO'),
        ('VALIDANDO', 'VALIDANDO'),
        ('PENDIENTE', 'PENDIENTE'),
    )
    ESTADO_CIVIL = (

        ('SOLTERA/O', 'SOLTERA/O'),
        ('CASADA/O', 'CASADA/O'),
    )
    REGIMEN = (
        ('NO APLICA', 'NO APLICA'),
        ('SEPARACIÓN DE BIENES', 'SEPARACIÓN DE BIENES'),
        ('SOCIEDAD CONYUGAL', 'SOCIEDAD CONYUGAL'),
    )


    # Datos del cliente
    username = None
    email = models.EmailField('Correo electrónico', unique=True)
    foto_file = models.FileField(_('Foto del cliente'), upload_to=user_directory_path, blank=True)
    telefono = models.CharField(_('Teléfono'), max_length=10, blank=True)
    calle = models.CharField(_('Calle'), max_length=50, blank=True)
    numero_exterior = models.CharField(_('Número exterior'), max_length=10, blank=True)
    numero_interior = models.CharField(_('Número interior'), max_length=10, blank=True)
    colonia = models.CharField(_('Colonia'), max_length=50, blank=True)
    delegacion_municipio = models.CharField(_('Delegación o Municipio'), max_length=50, blank=True)
    ciudad = models.CharField(_('Ciudad'), max_length=50, blank=True)
    estado = models.CharField(_('Estado'), max_length=50, blank=True)
    codigo_postal = models.IntegerField(_('Código postal'), blank=True, default=0)
    estado_civil = models.CharField(_('Estado civil'), max_length=10, choices=ESTADO_CIVIL, blank=True)
    regimen_conyugal = models.CharField(_('Régimen conyugal'), max_length=20, choices=REGIMEN, blank=True)
    rfc = models.CharField(_('RFC'), max_length=20, blank=True)
    razon_social = models.CharField(_('Razón social'), max_length =50, blank=True)
    domicilio_fiscal = models.CharField(_('Domicilio fiscal'), max_length=50, blank=True)
    curp = models.CharField(_('CURP'), max_length=30, blank=True)
    # Documentos del cliente
    identificacion_file = models.FileField(_('Identificación (INE ambos lados/Pasaporte)'), upload_to=user_directory_path, blank=True)
    curp_file = models.FileField(_('Cédula CURP'), upload_to=user_directory_path, blank=True)
    cedula_rfc_file = models.FileField(_('Cédula RFC'), upload_to=user_directory_path, blank=True)
    recibo_luz_file = models.FileField(_('Recibo de luz'), upload_to=user_directory_path, blank=True)
    comprobante_ingresos_file = models.FileField(_('Comprobante de ingresos (último año)'), upload_to=user_directory_path, blank=True)
    comprobante_domicilio = models.FileField(_('Comprobante de domicilio'), upload_to=user_directory_path, blank=True)
    # Datos y documentos del obligado solidario
    obligado_nombre = models.CharField(_('Nombre'), max_length=20, blank=True)
    obligado_apellido = models.CharField(_('Apellido'), max_length=20, blank=True)
    obligado_relacion = models.CharField(_('Relación'), max_length=20, blank=True)
    obligado_rfc = models.CharField(_('RFC'), max_length=20, blank=True)
    obligado_curp = models.CharField(_('CURP'), max_length=30, blank=True)
    obligado_identificacion_file = models.FileField(_('Identificación (INE ambos lados/Pasaporte)'), upload_to=user_directory_path, blank=True)
    obligado_rfc_file = models.FileField(_('Cédula RFC'), upload_to=user_directory_path, blank=True)
    obligado_curp_file = models.FileField(_('Cédula CURP'), upload_to=user_directory_path, blank=True)
    obligado_recibo_luz = models.FileField(_('Recibo de luz'), upload_to=user_directory_path, blank=True)
    obligado_comprobante_domicilio = models.FileField(_('Comprobante de domicilio'), upload_to=user_directory_path, blank=True)
    #Datos del plan de finaciamiento
    plan_elegido = models.CharField(_('Plan de financiamiento elegido'), max_length=20, blank=True)
    monto_credito = models.CharField(_('Monto del crédito'), max_length=20, blank=True)
    numero_de_paneles = models.CharField(_('Cantidad de paneles'), max_length=10, blank=True)
    enganche = models.CharField(_('Enganche'), max_length=20, blank=True)
    numero_de_pagos = models.CharField(_('Cantidad de pagos'), max_length=5, blank=True)
    pago_mensual = models.CharField(_('Pago mensual'), max_length=20, blank=True)
    estado_del_financiamiento = models.CharField(_('Estatus del financiamiento'), max_length=9, choices=ESTATUS_FINANCIAMIENTO, default='PENDIENTE')
    consumo_kw_promedio = models.CharField(_('Consumo promedio Kw'), max_length=20, blank=True)
    importe_promedio_cfe = models.CharField(_('Importe promedio CFE'), max_length=20, blank=True)
    terms = models.BooleanField(_('Acepto los términos y condiciones'),
        error_messages={'required': 'Debes aceptar los términos y condiciones'}, blank=True, default=False
    )
    #Campos de verificación de cuenta, perfil completo y autorización de consulta en buró de crédito
    mail_confirmed = models.BooleanField(_('Correo electrónico confirmado'), blank=True, default=False)
    perfil_completo = models.BooleanField(_('Información de perfil completa'), blank=True, default=False)
    autorizacion_buro_credito = models.BooleanField(_('Autorizo a Eco Luz a consultar mi información crediticia'), error_messages={'required': 'Debes marcar esta casilla para poder continuar'}, blank=True, default=False)
    fecha_autorizacion_de_consulta = models.DateField(_('Fecha de autorización de consulta de información crediticia'), blank=True, null=True)
    hora_autorizacion_de_consulta = models.TimeField(_('Hora de autorización de consulta de información creditica'), blank=True, null=True)
    fecha_de_consulta_buro = models.DateField(_('Fecha de consulta de información crediticia'), blank=True, null=True)
    hora_de_consulta_buro = models.TimeField(_('Hora de consulta de información crediticia'), blank=True, null=True)
    tipo_usuario = models.CharField(_('tipo usuario'), max_length=12, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

bots/forms.py
#-*- coding: utf-8 -*-
from django import forms
from django.utils.translation import gettext_lazy as _

#Aquí se definen los campos de los diferentes formularios que se usan en la plataforma
class ConoceTuAhorroForm(forms.Form):
    nombre = forms.CharField(label=_("Nombre"), widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=30, required=True)
    rpu = forms.IntegerField(label=_("Número de servicio"), widget=forms.NumberInput(attrs={'class': 'form-control'}), min_value=0, max_value=999999999999, required=True)
    tarifa = forms.CharField(label=_("Tipo de tarifa"), widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=5, required=True)


class DatosDeConsumoForm(forms.Form):
    numero_de_paneles = forms.DecimalField(label=_("Cantidad de paneles necesarios"), widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'True'}), decimal_places=2)
    consumo_kw_mes = forms.DecimalField(label=_("Consumo mensual promedio de Kw"), widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'True'}), decimal_places=2)
    importe_promedio = forms.DecimalField(label=_("Importe mensual promedio"), widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'True'}), decimal_places=2)
    credito = forms.DecimalField(label=_("Monto del crédito"), widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'True'}), decimal_places=2)


class CotizacionForm(forms.Form):
    plan_cot = forms.CharField(label=_("Nombre"), widget=forms.TextInput(
        attrs={'readonly': 'True', 'type': 'hidden'}), max_length=30, required=True)

    numero_de_paneles_cot = forms.IntegerField(label=_("Número de paneles"), widget=forms.TextInput(
        attrs={'readonly': 'True', 'type': 'hidden'}))

    consumo_kw_mes_cot = forms.DecimalField(label=_("Monto del crédito"), widget=forms.TextInput(
        attrs={'readonly': 'True', 'type': 'hidden'}), decimal_places=2)

    importe_mensual_cfe_cot = forms.DecimalField(label=_("Monto del crédito"), widget=forms.TextInput(
        attrs={'readonly': 'True', 'type': 'hidden'}), decimal_places=2)

    credito_cot = forms.DecimalField(label=_("Monto del crédito"), widget=forms.TextInput(
        attrs={'readonly': 'True', 'type': 'hidden'}), decimal_places=2)

    enganche_cot = forms.DecimalField(label=_("Enganche"), widget=forms.TextInput(
        attrs={'readonly': 'True', 'type': 'hidden'}), decimal_places=2)

    numero_de_pagos_cot = forms.IntegerField(label=_("Número de pagos mensuales"), widget=forms.TextInput(
        attrs={'readonly': 'True'}))

    pago_mensual_cot = forms.DecimalField(label=_("Pago mensual"),
                                          widget=forms.TextInput(attrs={'readonly': 'True'}),
                                          decimal_places=2)


class CalculadoraForm(forms.Form):
    ahorro_previo = forms.NumberInput()
    numero_de_pagos = forms.IntegerField(label=_("Número de pagos mensuales"), widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'True'}))
    pago_mensual = forms.DecimalField(label=_("Pago mensual"), widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'True'}), decimal_places=2)


class PlanForm(forms.Form):
    plan = forms.CharField(label=_("Plan elegido"), widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'True'}), max_length=20)
    monto_credito = forms.DecimalField(label=_("Monto del crédito"), widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'True'}), decimal_places=2)
    eng = forms.DecimalField(label=_("Enganche"), widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'True'}), decimal_places=2)
    paneles = forms.DecimalField(label=_("Número de paneles"), widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'True'}), decimal_places=0)
    mensualidad = forms.DecimalField(label=_("Pago mensual"), widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'True'}), decimal_places=2)
    num_pagos = forms.DecimalField(label=_("Número de mensualidades"), widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'True'}), decimal_places=2)
    consumo_kw = forms.DecimalField(label=_("Monto del crédito"), widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'True', 'type': 'hidden'}), decimal_places=2)
    importe_mens_cfe = forms.DecimalField(label=_("Monto del crédito"), widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'True', 'type': 'hidden'}), decimal_places=2)

bots/templates/bots/gracias-cotizacion.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}Tu plan de financiamiento{% endblock %}
<!--<body class="body-back-calculadora">-->
 {% block class-body %}body-back-calculadora{% endblock %}

    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12" style="margin-top: 100px">
                <div class="row">
                    <div class="col-sm-12">
                        <h3 class="strong-white">TU PLAN DE FINANCIAMIENTO ECOLUZ</h3>
                        <br> </div>
                    <div class="col-sm-offset-1 col-sm-10" style="background-color: #e5e5e5;">
                        <br>
                        <p class="text-justify">
                            <br> ¡Felicidades! Ya has elegido tu plan de financiamiento <strong class="strong-green">ECO LUZ</strong>. El siguiente paso consiste en realizar tu evaluación financiera, para hacerlo vamos a necesitar información adicional la cual deberás ingresar en tu Perfil Ecoluz.
                            <br>
                        <!---->
                            <!--<h3 class="strong-green">Detalles de tu plan de financiamiento Ecoluz</h3>-->
                            <!--<div class="col-sm-6 col-sm-offset-3">-->
                            <!--<div id="div_id_estado_del_financiamiento" class="form-group"> <label for="id_estado_del_financiamiento" class="control-label ">Estatus del financiamiento</label>-->
                                <!--<div class="controls "> <input type="text" name="plan_elegido" disabled="True" id="id_estado_del_financiamiento" value="PENDIENTE" class="textinput textInput form-control" maxlength="20"></div> </div>-->

                            <!--<div id="div_id_plan_elegido" class="form-group"> <label for="id_plan_elegido" class="control-label ">Plan de financiamiento elegido</label>-->
                            <!--<div class="controls "> <input type="text" name="plan_elegido" disabled="True" id="id_plan_elegido" value="{{ user.plan_elegido }}" class="textinput textInput form-control" maxlength="20"> </div> </div>-->

                            <!--<div id="div_id_monto_credito" class="form-group"> <label for="id_monto_credito" class="control-label ">Monto del crédito</label>-->
                            <!--<div class="controls "> <input type="text" name="monto_credito" disabled="True" id="id_monto_credito" value="{{ user.monto_credito }}" class="textinput textInput form-control" maxlength="20"> </div> </div>-->

                            <!--<div id="div_id_numero_de_paneles" class="form-group"> <label for="id_numero_de_paneles" class="control-label ">Cantidad de páneles</label>-->
                            <!--<div class="controls "> <input type="text" name="numero_de_paneles" disabled="True" id="id_numero_de_paneles" value="{{ user.numero_de_paneles }}" class="textinput textInput form-control" maxlength="10"> </div> </div>-->

                            <!--<div id="div_id_enganche" class="form-group"> <label for="id_enganche" class="control-label ">Enganche</label>-->
                            <!--<div class="controls "> <input type="text" name="enganche" disabled="True" id="id_enganche" value="{{ user.enganche }}" class="textinput textInput form-control" maxlength="20"> </div> </div>-->

                            <!--<div id="div_id_numero_de_pagos" class="form-group"> <label for="id_numero_de_pagos" class="control-label ">Cantidad de pagos</label>-->
                            <!--<div class="controls "> <input type="text" name="numero_de_pagos" disabled="True" id="id_numero_de_pagos" value="{{ user.numero_de_pagos }}" class="textinput textInput form-control" maxlength="5"> </div> </div>-->

                            <!--<div id="div_id_pago_mensual" class="form-group"> <label for="id_pago_mensual" class="control-label ">Pago mensual</label>-->
                            <!--<div class="controls "> <input type="text" name="pago_mensual" disabled="True" id="id_pago_mensual" value="{{ user.pago_mensual }}" class="textinput textInput form-control" maxlength="20"> </div> </div>-->
                            Asimismo, deberás incluir en tu perfil los siguientes documentos en formato PDF:
                            <ul class="text-justify">
                                <li>Recibo de luz más reciente</li>
                                <li>identificaión. Puede ser pasaporte vigente o credencial del INE por ambos lados</li>
                                <li>Cédula RFC</li>
                                <li>CURP</li>
                                <li>Comprobante de domicilio (recibo de teléfono/celular, gas, agua, predial, estados de cuenta bancarios)</li>
                                <li>Comprobante ingresos del último año</li>
                                <li>Una fotografía tuya en formato PNG o JPG</li>
                                <li>Datos de un obligado solidario (aval)</li>
                                <li>Identificación del aval. Pasaporte vigente o credencial del INE por ambos lados</li>
                                <li>CURP del aval</li>
                                <li>Cédula RFC del aval</li>
                                <li>Último recibo de luz del aval</li>
                                <li>Comprobante de domicilio del aval</li>
                            </ul>
                            <br>Adicionalmente, te hemos enviado un correo con esta información.
                            <br>
                            <div class="form-group col-sm-offset-1"> <a href="{% url 'clientes:editar_perfil' %}" class="btn btn-primary" style="color: #fff !important;">IR A MI PERFIL PARA COMPLETAR LA INFORMACIÓN</a> </div>
                            </div>
                            <br>
                        </p>
                        <br> </div>
                </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br> </div>
   {% endblock %}
    <!-- End container -->
    <!-- Start footer -->
    {% block footer %}
    {% include 'footer/_footer-sections.html' %}
    {% endblock %}
    <!-- End footer -->
    {% block js-special %}

    {% endblock %}

bots/templates/bots/tu_cotizacion.html
<div class="container">
        <div class="row">
            <div class="col-sm-12" style="margin-top: 100px">
                <div class="row">
                    <div class="col-sm-12">
                        <h3 class="strong-white">TU PLAN DE FINANCIAMIENTO ECOLUZ</h3>
                        <br> </div>
                    <div class="col-sm-offset-1 col-sm-10" style="background-color: #e5e5e5;">
                        <br>
                        <p class="text-justify">
                            <br> ¡Felicidades! Ya has elegido tu plan de financiamiento <strong class="strong-green">ECO LUZ</strong>. El siguiente paso consiste en realizar tu evaluación financiera, para hacerlo vamos a necesitar información adicional la cual deberás ingresar en tu Perfil Ecoluz.
                            <br>
                            <h3 class="strong-green">Detalles de tu plan de financiamiento Ecoluz</h3>
                            <div class="col-sm-6 col-sm-offset-3">
                            <div id="div_id_estado_del_financiamiento" class="form-group"> <label for="id_estado_del_financiamiento" class="control-label ">Estatus del financiamiento</label>
                                <div class="controls "> <input type="text" name="plan_elegido" disabled="True" id="id_estado_del_financiamiento" value="PENDIENTE" class="textinput textInput form-control" maxlength="20"></div> </div>

                            <div id="div_id_plan_elegido" class="form-group"> <label for="id_plan_elegido" class="control-label ">Plan de financiamiento elegido</label>
                            <div class="controls "> <input type="text" name="plan_elegido" disabled="True" id="id_plan_elegido" value="{{ user.plan_elegido }}" class="textinput textInput form-control" maxlength="20"> </div> </div>

                            <div id="div_id_monto_credito" class="form-group"> <label for="id_monto_credito" class="control-label ">Monto del crédito</label>
                            <div class="controls "> <input type="text" name="monto_credito" disabled="True" id="id_monto_credito" value="{{ user.monto_credito }}" class="textinput textInput form-control" maxlength="20"> </div> </div>

                            <div id="div_id_numero_de_paneles" class="form-group"> <label for="id_numero_de_paneles" class="control-label ">Cantidad de páneles</label>
                            <div class="controls "> <input type="text" name="numero_de_paneles" disabled="True" id="id_numero_de_paneles" value="{{ user.numero_de_paneles }}" class="textinput textInput form-control" maxlength="10"> </div> </div>

                            <div id="div_id_enganche" class="form-group"> <label for="id_enganche" class="control-label ">Enganche</label>
                            <div class="controls "> <input type="text" name="enganche" disabled="True" id="id_enganche" value="{{ user.enganche }}" class="textinput textInput form-control" maxlength="20"> </div> </div>

                            <div id="div_id_numero_de_pagos" class="form-group"> <label for="id_numero_de_pagos" class="control-label ">Cantidad de pagos</label>
                            <div class="controls "> <input type="text" name="numero_de_pagos" disabled="True" id="id_numero_de_pagos" value="{{ user.numero_de_pagos }}" class="textinput textInput form-control" maxlength="5"> </div> </div>

                            <div id="div_id_pago_mensual" class="form-group"> <label for="id_pago_mensual" class="control-label ">Pago mensual</label>
                            <div class="controls "> <input type="text" name="pago_mensual" disabled="True" id="id_pago_mensual" value="{{ user.pago_mensual }}" class="textinput textInput form-control" maxlength="20"> </div> </div>
                            Asimismo, deberás incluir en tu perfil los siguientes documentos en formato PDF:
                            <ul class="text-justify">
                                <li>Recibo de luz más reciente</li>
                                <li>identificaión. Puede ser pasaporte vigente o credencial del INE por ambos lados</li>
                                <li>Cédula RFC</li>
                                <li>CURP</li>
                                <li>Comprobante de domicilio (recibo de teléfono/celular, gas, agua, predial, estados de cuenta bancarios)</li>
                                <li>Comprobante ingresos del último año</li>
                                <li>Una fotografía tuya en formato PNG o JPG</li>
                                <li>Datos de un obligado solidario (aval)</li>
                                <li>Identificación del aval. Pasaporte vigente o credencial del INE por ambos lados</li>
                                <li>CURP del aval</li>
                                <li>Cédula RFC del aval</li>
                                <li>Último recibo de luz del aval</li>
                                <li>Comprobante de domicilio del aval</li>
                            </ul>
                            <br>
                            <br>
                            <div class="form-group col-sm-offset-1"> <a href="http://{{ domain }}{% url 'clientes:editar_perfil' %}" class="btn btn-primary" style="color: #fff !important;">IR A MI PERFIL PARA COMPLETAR LA INFORMACIÓN</a> </div>
                            </div>
                            <br>
                        </p>
                        <br> </div>
                </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br> </div>