bots/urls.py
from django.conf.urls import url

from . import views
app_name = 'bots'
urlpatterns = [
    url(r'^$', views.index, name='index-calc'),
    url(r'^consulta/$', views.consulta_datos_servicio, name='consulta'),
    url(r'^resultados/$', views.resultados, name='resultados'),
    url(r'^calculadora/$', views.Calculadora.as_view(), name='calculadora'),
    url(r'^procesar/$', views.procesar_opcion, name='procesar'),
    url(r'^plan-express/$', views.ProcesarPlanView.as_view(), name='plan-express'),
    url(r'^plan-moderado/$', views.ProcesarPlanView.as_view(), name='plan-moderado'),
    url(r'^plan-largo-plazo/$', views.ProcesarPlanView.as_view(), name='plan-lp'),
    url(r'^tu-cotizacion/$', views.TuCotizacion.as_view(), name='tu-cotizacion'),
]

ecoluz/urls.py
# -*- coding: utf-8 -*-
"""ecoluz URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from ecoluzweb import views
from django.conf import settings
from django.conf.urls.static import static
from . import views as vw
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)


urlpatterns = [
    url(r'^eco-v1/', admin.site.urls),
    url(r'^$', views.inicio, name='inicio'),
    url(r'^clientes/', include('clientes.urls')),
    url(r'^usuarios/', include('usuarios.urls'), name='usuarios'),
    url(r'^ecoclientes/', include('ecoclientes.urls'), name='ecoclientes'),
    url(r'^conoce-tu-ahorro/', include('bots.urls'), name='conoce-tu-ahorro'),
    url(r'^proyectos/', views.proyectos, name='proyectos'),
    url(r'^que-es-ecoluz/', views.que_es_ecoluz, name='que-es-ecoluz'),
    url(r'^terminos-y-condiciones', views.terminos_y_condiciones, name='terminos-y-condiciones'),
    url(r'^aviso-de-privacidad', views.aviso_de_privacidad, name='aviso-de-privacidad'),
    url(r'^contacto', views.contacto, name='contacto'),
    url(r'^ingresando', vw.wherenext, name='ingresando'),

    url('^reestablecer-contrasena/$', auth_views.password_reset,
        {
            'template_name': 'clientes/password_reset_form.html',
            'html_email_template_name': 'clientes/password_reset_email.html',
        }, name='password_reset'),
    url(r'^reestablecer-contrasena/listo/$',
        PasswordResetDoneView.as_view(template_name='clientes/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reestablecer-contrasena/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='clientes/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reestablecer-contrasena/hecho/$',
        PasswordResetCompleteView.as_view(template_name='clientes/password_reset_complete.html'),
        name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
)

from . import views
app_name = 'usuarios'
urlpatterns = [
    url(r'^acceso/$', login, {'template_name': 'usuarios/login.html'}, name='acceso'),
    url(r'^adios/$', logout, {'template_name': 'usuarios/logout.html'}, name='adios'),
    url(r'^registro/$', views.registro, name='registro'),
    url(r'^perfil/$', views.perfil, name='perfil'),
    url(r'^perfil/editar/$', views.editar_perfil, name='editar_perfil'),
    url(r'^cambiar-contrasena/$', views.cambiar_contrasena, name='cambiar_contrasena'),
    url(r'^reestablecer-contrasena/$', password_reset, {'template_name': 'usuarios/reestablecer-contrasena.html'},  name='reestablecer-contrasena'),
    url(r'^reestablecer-contrasena/listo/$', password_reset_done, name='password_reset_done'),
    url(r'^reestablecer-contrasena/confirmar/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^reestablecer-contrasena/hecho/$', password_reset_complete, {'template_name': 'usuarios/password_rscmp.html'}, name='password_rscmp'),
]

usuarios/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from usuarios.models import Usuario
from clientes.models import Cliente
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from crispy_forms.bootstrap import TabHolder, Tab
from . import models
import clientes.models



class FormaDeCreacion(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Campo obligatorio.', label="Nombre")
    last_name = forms.CharField(max_length=30, required=True, help_text='Campo obligatorio.', label="Apellidos")
    email = forms.EmailField(max_length=254,required=True,label='Correo electrónico', help_text='Este campo es la clave de ingreso. No podrá modificarse posteriormente.')
    password1 = forms.CharField(widget=forms.PasswordInput() , required=True, label='Contraseña.')
    password2 = forms.CharField(widget=forms.PasswordInput(), required=True, label='Vuelva a ingresar su contraseña.')
    terms = forms.BooleanField(
        error_messages={'required': 'Debes aceptar los términos y condiciones'},
        label="Acepto los términos y condiciones"
    )
    #tipo_usuario = forms.CharField(label='tipo_usuario', widget=forms.TextInput( attrs= {'type' : 'hidden' }), required=False )

    class Meta:
        model = Cliente
        fields = (
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
            'terms',
            #'tipo_usuario'
        )


class CommonFormHelper(FormHelper):
    def __init__(self):
        super(CommonFormHelper, self).__init__()
        self.disable_csrf = True
        self.form_tag = False


class FormaEditarClienteU(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = (
            'first_name',
            'last_name',
            'telefono',
            'rfc',
            'razon_social',
            'domicilio_fiscal',
            'calle',
            'numero_exterior',
            'numero_interior',
            'colonia',
            'delegacion_municipio',
            'ciudad',
            'estado',
            'codigo_postal',
            'curp',
            'perfil_completo',
        )

    def __init__(self, *args, **kwargs):
        self.helper_name_info = CommonFormHelper()
        self.helper_name_info.layout = Layout(
            Tab('infos',
                Field('first_name', css_class='form-control-white'),
                Field('last_name', css_class='form-control-white'),
                Field('telefono', css_class='form-control-white'),
                Field('calle', css_class='form-control-white'),
                Field('numero_exterior', css_class='form-control-white'),
                Field('numero_interior', css_class='form-control-white'),
                Field('colonia', css_class='form-control-white'),
                Field('delegacion_municipio', css_class='form-control-white'),
                Field('ciudad', css_class='form-control-white'),
                Field('estado', css_class='form-control-white'),
                Field('codigo_postal', css_class='form-control-white'),
                Field('rfc', css_class='form-control-white', pattern="^[a-zA-Z]{4}\d{6}[a-zA-Z0-9]{3}$",
                      title="Debe escribir un RFC con el formato válido."),
                Field('razon_social', css_class='form-control-white'),
                Field('domicilio_fiscal', css_class='form-control-white'),
                Field('curp', css_class='form-control-white',
                      pattern="^[a-zA-Z]{4}\d{6}[a-zA-Z]{5}[a-zA-Z0-9]{3}$",
                      title="Debe escribir una CURP con el formato válido."),
                Field('perfil_completo', type="hidden"),
            ),
        )

        super(FormaEditarClienteU, self).__init__(*args, **kwargs)


class FormaEditarUsuario(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = (
            'a_identificacion',
            'a_identificacion_beneficiarios',
            'a_domicilio_negocio',
            'a_domicilio_fiscal',
            'a_RFC',
            'a_CURP',
            'foto_negocio',
            'a_buro',
            'a_curriculum',
            'foto_dar',
            'a_estados_cuenta',
            'a_declaraciones',
            'a_constitutiva',
            'a_rpc',
            'rfc_pm',
            'domicilio_fiscal_pm',
            'id_representante',
            'estado_cuenta',
            'bio',
        )

    def __init__(self, *args, **kwargs):
        self.helper_some_info = CommonFormHelper()
        self.helper_some_info.layout = Layout(
            Tab('subir-docs',
                'DAR_id',
                'plazas',
                'a_identificacion',
                'a_identificacion_beneficiarios',
                'a_domicilio_negocio',
                'a_domicilio_fiscal',
                'a_RFC',
                'a_CURP',
                'foto_negocio',
                'a_buro',
                'a_curriculum',
                'foto_dar',
                'a_estados_cuenta',
                'a_declaraciones',
                'a_constitutiva',
                'a_rpc',
                'rfc_pm',
                'domicilio_fiscal_pm',
                'id_representante',
                'estado_cuenta',
                'bio',
                #InlineRadios('HypertensionHX'),
            ),
        )

        # self.helper_some_other_info = CommonFormHelper()
        # self.helper_some_other_info.layout = Layout(
        #     Tab(
        #         'Tab 4',
        #         'some_other_field_or_whatevere_you_want_here',
        #     ),
        #)
        super(FormaEditarUsuario, self).__init__(*args, **kwargs)


#
# class FormaEditarClienteU(forms.ModelForm):
#     # username = forms.CharField(max_length=12, required=True, help_text='Campo obligatorio.', label="Nombre de usuario")
#     # first_name = forms.CharField(max_length=30, required=True, help_text='Campo obligatorio.', label="Nombre")
#     # last_name = forms.CharField(max_length=30, required=True, help_text='Campo obligatorio.', label="Apellidos")
#     # email = forms.EmailField(max_length=254,required=True, help_text='Ingrese su dirección de correo electrónico.')
#
#     class Meta:
#
# class FormaEditarUsuario(forms.ModelForm):
#     helper = FormHelper()
#     helper.form_tag = False
#     helper.layout = Layout(
#         TabHolder(
#             Tab(
#
#             ),
#             Tab(# Documentos del cliente
#
#                 )
#             )
#         )
#
#     class Meta:
#         model = Usuario
#         fields = [
#         ]


#
# #
# #
# class FormaEditarUser(forms.ModelForm):
#     class Meta:
#         model = Usuario
#         fields = ('first_name', 'last_name', 'email' , 'foto_file')
#
#
# class FormaEditarPerfil(forms.ModelForm):
#     helper = FormHelper()
#     helper.form_tag = False
#     helper.layout = Layout(
#         TabHolder(
#             Tab(
#                 'Mis datos',
#                 Field('first_name', css_class='form-control-white'),
#                 Field('last_name', css_class='form-control-white'),
#                 'foto_file',
#                 Field('telefono', css_class='form-control-white'),
#             ),
#         )
#     )
#
#     class Meta:
#         model = Usuario
#         fields = [
#             'first_name',
#             'last_name',
#             'foto_file',
#             'telefono',
#         ]
#
#
# class FormaVerPerfil(forms.ModelForm):
#     helper = FormHelper()
#     helper.form_tag = False
#     helper.layout = Layout(
#         TabHolder(
#             Tab(
#                 'Mis datos',
#                 'first_name',
#                 'last_name',
#                 'foto_file',
#                 'telefono',
#             ),
#
#         )
#     )
#
#     class Meta:
#         model = Usuario
#         fields = [
#             'first_name',
#             'last_name',
#             'foto_file',
#             'telefono',
#         ]

usuarios/templates/usuarios/base-eco.html
<!DOCTYPE html>
{% load static %}
<html lang="es">

<head>

    {% include 'head/_metas.html' %}
    <title>Eco en línea | {% block head_title %}{% endblock %}</title>
    {% include 'head/_links-head.html' %}
    {% block css-special %}
    {% endblock %}

    {% block head-eco %}
    {% endblock %}

</head>

<body class="{% block class-body %}{% endblock %}">
    <!-- Start header navbar -->
        {% include 'usuarios/navbar-eco.html' %}
    <!-- End header navbar -->
    <!-- Start container carousel -->
    {% block content %}
    {% endblock %}
    <!-- End container carousel -->
    <!-- Start button chat fixed desktop
    {% include 'footer/_chatBtn-desktop.html' %}
    <!-- End button chat fixed desktop -->
    <!-- Start footer -->
    {% block footer %}
    {% endblock %}
    <!-- End footer -->
    <!-- Start Scripts JS -->
    {% include 'scripts/_scripts-js.html' %}
    {% block js-special %}
    {% endblock %}
</body>

</html>

usuarios/templates/usuarios/logout.html
{% extends "usuarios/base-eco.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}Acceso a Clientes{% endblock %}

    {% block content %}
     <div class="container">
        <div class="row">
            <div class="col-sm-12" style="margin-top: 100px">
                    <div class="col-sm-12" style="background-color: #e5e5e5;">
                        <br>
                            <div class="form-group">
                                <div class="row">
                                <div class="col-md-7 ">

                                    <br>Has cerrado sesión correctamente.
                                    <br>Vuelve pronto :)
                                </div>
                                </div>
                            </div>
                        <br> </div>
                    <br> </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br> </div>

    {% endblock %}
    <!-- End container -->
    <!-- Start footer -->
    {% block footer %}
    {% include 'footer/_footer-sections.html' %}
    {% endblock %}
    <!-- End footer -->
    {% block js-special %}

    {% endblock %}

usuarios/templates/usuarios/perfil.html
{% extends "usuarios/base-eco.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block head_title %} Mi Perfil {% endblock %}

{% block head-eco %}

<!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/r/bs-3.3.5/jq-2.1.4,dt-1.10.8/datatables.min.css"/>-->

<!--<script type="text/javascript" src="https://cdn.datatables.net/r/bs-3.3.5/jqc-1.11.3,dt-1.10.8/datatables.min.js">-->
<!--</script>-->




{% endblock %}



<body class="">
	<!-- Start header navbar -->
	<nav class="navbar navbar-default navbar-fixed white no-background bootsnav">
		<!-- Start Top Search
        <div class="top-search">
            <div class="container">
                <div class="input-group"> <span class="input-group-addon"><i class="fa fa-search fa-2x"></i></span>
                    <input type="text" class="form-control" placeholder="Buscar..."> <span class="input-group-addon close-search"><i class="fa fa-times fa-lg"></i></span> </div>
            </div>
        </div>
         End Top Search -->
	</nav>{% block content %}
	<div class="container" style="width: 90%; !important;">
		<div class="row">
			<div class="col-sm-12" style="margin-top: 100px">
				<div class="col-md-12" style="width: 100%">
					<br>
					<div class="form-group">
						<div class="row">
							<div class="row">
								<a class="btn btn-primary col-md-2 col-md-offset-1" href="/usuarios/perfil" style="color: #fff !important;"><span>VER MI PERFIL</span></a>
                                <a class="btn btn-primary col-md-2 col-md-offset-1" href="/usuarios/perfil/editar" style="color: #fff !important;">EDITAR MI PERFIL</a>
                                <a class="btn btn-primary col-md-2 col-md-offset-1" href="/usuarios/cambiar-contrasena" style="color: #fff !important;">CAMBIAR CONTRASEÑA</a>
                                <a class="btn btn-warning col-md-1 col-md-offset-1" href="/usuarios/adios" style="color: #fff !important;">SALIR</a>
							</div><!--<div class="col-md-4">-->
							<!--<div class="row">-->
							<!--<p><a class="btn btn-primary col-md-8 col-md-offset-2" style="color: #fff !important;" href="/usuarios/perfil"><span>VER MI PERFIL</span></a></p>-->
							<!--</div>-->
							<!--<br>-->
							<!--<div class="row">-->
							<!--<p><a class="btn btn-primary col-md-8 col-md-offset-2" style="color: #fff !important;" href="/usuarios/perfil/editar">EDITAR INFORMACIÓN DE MI PERFIL</a></p>-->
							<!--</div>-->
							<!--<br>-->
							<!--<div class="row">-->
							<!--<p><a class="btn btn-primary col-md-8 col-md-offset-2" style="color: #fff !important;" href="/usuarios/cambiar-contrasena">CAMBIAR CONTRASEÑA</a></p>-->
							<!--</div>-->
							<!--<br>-->
							<!--<div class="row">-->
							<!--<p><a class="btn btn-warning col-md-8 col-md-offset-2" style="color: #fff !important;" href="/usuarios/adios">SALIR</a></p>-->
							<!--</div>-->
							<!--</div>-->
							<div class="col-md-11">
   								<br>
								<br>

								<h4>PORTAL DE USUARIO DEL ECO</h4><br>
								<br>
								{% if messages %}
								<div class="row">
									<div class="col-md-2"></div>
									<div class="alert alert-info col-md-5 alert-dismissable">
										<a aria-label="close" class="close" data-dismiss="alert" href="#">&times;</a> {% for message in messages %} {{ message }} {% endfor %}
									</div>
									<div class="col-md-2"></div>
								</div>{% endif %} <!-- Empiezan Tabs -->
								<form class="mainForm" enctype="multipart/form-data">
									<ul class="nav nav-tabs">
										<li class="tab-pane active">
											<a data-toggle="tab" href="#mis-datos">Mis datos</a>
										</li>
										<li class="tab-pane">
											<a data-toggle="tab" href="#capacitacion">Capacitación</a>
										</li>
										<li class="tab-pane">
											<a data-toggle="tab" href="#cronograma">Cronograma de trabajo</a>
										</li>
										<li class="tab-pane">
											<a data-toggle="tab" href="#registro-nuevos">Mis créditos</a>
										</li>
									</ul>
									<div class="tab-content panel-body">
										<div class="tab-pane active" id="mis-datos">
											<div class="form-group" id="div_id_first_name">
												<label class="control-label" for="id_first_name">Nombre</label>
												<div class="controls">
													<input class="textinput textInput form-control" disabled="true" id="id_first_name" maxlength="30" name="first_name" type="text" value="{{ user.first_name }}">
												</div>
											</div>
											<div class="form-group" id="div_id_last_name">
												<label class="control-label" for="id_last_name">Apellidos</label>
												<div class="controls">
													<input class="textinput textInput form-control" disabled="true" id="id_last_name" maxlength="30" name="last_name" type="text" value="{{ user.last_name }}">
												</div>
											</div>
											<div class="form-group" id="div_id_foto_file">
												<label class="control-label">Foto</label> {% if usuario.foto_dar %}
												<div class="controls">
													<a class="btn btn-default" href="{{ usuario.foto_dar.url }}" target="_blank">VER ARCHIVO</a>
												</div>{% else %}
												<div class="controls">
													<span>NO HAY FOTO DEL USUARIO</span>
												</div>{% endif %}
											</div>
										</div>
										<div class="tab-pane" id="capacitacion">
											<p>0. Introducción <a href="https://drive.google.com/drive/folders/0Bznn6eCtxLBKM2IzYUtLVTRRMW8" target="_blank">AQUÍ</a>.</p><br>
												<p>		ECOLUZ </p> <iframe allowfullscreen frameborder="0" height="315" src="https://www.youtube.com/embed/gJ8v1l9mfkI" width="560"></iframe>
											<p>1. Módulo ventas: modelo de negocio <a href="https://drive.google.com/drive/folders/0Bznn6eCtxLBKM2IzYUtLVTRRMW8" target="_blank">AQUÍ</a>.</p><br>
											<p>2. Módulo producto: datos técnicos <a href="https://drive.google.com/drive/folders/0Bznn6eCtxLBKM2IzYUtLVTRRMW8" target="_blank">AQUÍ</a>.</p><br>
											<p>3. Módulo proceso de operación DAR <a href="https://drive.google.com/drive/folders/0Bznn6eCtxLBKM2IzYUtLVTRRMW8" target="_blank">AQUÍ</a>.</p><br>
											<p>4. Módulo de sistemas <a href="https://drive.google.com/drive/folders/0Bznn6eCtxLBKM2IzYUtLVTRRMW8" target="_blank">AQUÍ</a>.</p><br>
											<p>5. Módulo de finanzas <a href="https://drive.google.com/drive/folders/0Bznn6eCtxLBKM2IzYUtLVTRRMW8" target="_blank">AQUÍ</a>.</p><br>

											<p>MANUAL OPERATIVO DAR</p><iframe allowfullscreen frameborder="0" height="315" src="https://www.youtube.com/embed/yqEtFZ2OZkY" width="560"></iframe><br>
											<br>
											<p></p>
										</div>



										<div class="tab-pane" id="cronograma">
											<p>AQUÍ ESTARÍA EL CRONOGRAMA DE TRABAJO ECOLUZ-DAR</p>
										</div>
										<div class="tab-pane" id="registro-nuevos">
											<div class="container" style="margin-left: 0%; margin-right:0%; width:97%;">
												<div class="row">
													<br>
													<br>
													 <table id="example" class="display" cellspacing="0" >
                <thead>
                <tr>
                    <th>FXF</th>
                    <th >CRÉDITO</th>
                    <th >BENEFICIARIO</th>
                    <th >ESTATUS</th>
					<th ><font size="2">FECHA COMPRA</font></th>
                    <th >#</th>
					<th ><font size="2">EQUIPOS</font></th>
                    <th >SUBTOTAL</th>
                    <th > <font size="2">FINANCIA-MIENTO </font></th>
					<th > <font size="2">PAGO TOTAL</font></th>
                    <th ># DÍAS</th>
                    <th >COM DAR</th>
					<th ><font size="2">ADEUDOS</font></th>
                    <th >OBSERVACIONES</th>
                </tr>
                </thead>
                <tbody>
                {% for eco_registro in registros %}
				<tr><td> <font size="2">{{ eco_registro.fxf_eqp }} </a></font> </td>
                    <td><font size="1">{{ eco_registro.numero_credito }}</font></td>
                    <td><font size="1">{{ eco_registro.nombre_beneficiario }}</font></td>
                    <!--<td>{{ eco_registro.patrocinado }}</td>-->
                    <td><font size="1">{{ eco_registro.estatus }}</font></td>
                    <td><font size="1">{{ eco_registro.fecha_compra | date:"d/m/y"  }}</font></td>
                    <td>{{ eco_registro.cantidad }}</td>
                    <td><font size="1">{{ eco_registro.modelo_equipo  }}</font></td>
                    <td>${{ eco_registro.subtotal_equipo |floatformat:2|intcomma  }}</td>
                    <td>${{ eco_registro.financiamiento_e |floatformat:2|intcomma  }}</td>
                    <td>${{ eco_registro.pago_total_e |floatformat:2|intcomma  }}</td>
                    <td> {{ eco_registro.fxf_eqp.numero_dias  }}</td>
                    <td>${{ eco_registro.com_dar_e |floatformat:2|intcomma  }}</td>
                    <td>${{ eco_registro.adeudos_eq |floatformat:2|intcomma  }}</td>
                    <!--<td>-->
                        <!--<font size="2">-->
                        <!--{% if eco_registro.factura_ecoluz %}-->
                                      <!--<a href="{{ eco_registro.factura_ecoluz.url }}">Ecoluz</a>-->
                                  <!--{% else %}-->
                                      <!--<span>Ecoluz</span>-->
                                  <!--{% endif %} /-->
                                  <!--{% if eco_registro.factura_fab %}-->
                                      <!--<a href="{{ eco_registro.factura_fab.url }}">FAB</a>-->
                                  <!--{% else %}-->
                                      <!--<span>FAB</span>-->
                                  <!--{% endif %} /-->
                                  <!--{% if eco_registro.factura_costos_dar %}-->
                                      <!--<a href="{{ eco_registro.factura_costos_dar.url }}">DAR</a>-->
                                  <!--{% else %}-->
                                      <!--<span>DAR</span>-->
                                  <!--{% endif %} /-->
                                     <!--{% if eco_registro.factura_reg %}-->
                                      <!--<a href="{{ eco_registro.factura_reg.url }}">DAR</a>-->
                                  <!--{% else %}-->
                                      <!--<span>REG</span>-->
                                  <!--{% endif %}-->
                        <!--</font>-->
                    <!--</td>-->
                     <td>{{ eco_registro.obs_e }}</td>
                </tr>
                {% endfor %}

                </tbody>
            </table>
												</div>
											</div>
										</div>
									</div>
								</form><!-- End Tabs -->
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
    {% endblock %}
    <!-- End container -->

    <!-- Start footer -->
    {% block footer %}
    {% include 'footer/_footer-sections.html' %}
    {% endblock %}
    <!-- End footer -->


    {% block js-special %}
	<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#example').DataTable();
			} );
</script>

<script type="text/javascript">
	// For demo to fit into DataTables site builder...
	$('#example')
		.removeClass( 'display' )
		.addClass('table table-striped table-bordered');
</script>



    {% endblock %}

usuarios/templates/usuarios/registro.html
{% extends "usuarios/base-eco.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}Registrarme{% endblock %}

    {% block content %}
     <div class="container">
        <div class="row">
            <div class="col-sm-12" style="margin-top: 100px">
                    <div class="col-sm-12" style="background-color: #e5e5e5;">
                        <br>
                            <div class="form-group">
                                <div class="row">
                                <div class="container">
                                <div class="col-md-6 col-md-offset-3 ">
                                    <br><h2>REGISTRO DE USUARIOS</h2>
                                    <br><strong class="strong-green">Crear un nuevo usuario.</strong>
                                <br>
                                    <!-- {% if messages %}
                                        <ul>
                                            {% for message in messages %}
                                            <li>{{ message }}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %} -->
                                    <form method="post">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <button type="submit" class="btn btn-flat btn-primary">REGISTRARME</button>
                                        &nbsp; <span>¿Ya estás registrado?</span> <a class="btn bnt-flat strong-green"  href="{% url 'usuarios:acceso' %}">INGRESA A TU PERFIL</a>
                                            {% for error in field.errors %}
                                              <p style="color: red">{{ error }}</p>
                                            {% endfor %}
                                          </p>
                                      </form>
                                    </div>
                                </div>
                                </div>
                            </div>
                        <br> </div>
                    <br> </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br> </div>

    {% endblock %}
    <!-- End container -->
    <!-- Start footer -->
    {% block footer %}
    {% include 'footer/_footer-sections.html' %}
    {% include 'TYC_modal.html' %}
    {% endblock %}
    <!-- End footer -->
    {% block js-special %}
    <script type="text/javascript" src="{% static 'js/tyc.js' %}"></script>
    <script> $(document).ready(function(){
            $("#id_terms").after('Acepto los<a href="{% url 'terminos-y-condiciones' %}" target="_blank" id="terms"> Términos y condiciones</a>');
        });</script>
    {% endblock %}