bots/urls.py
from django.conf.urls import url

from . import views
app_name = 'bots'
urlpatterns = [
    url(r'^$', views.index, name='index-calc'),
    url(r'^consulta/$', views.consulta_datos_servicio, name='consulta'),
    url(r'^resultados/$', views.resultados, name='resultados'),
    url(r'^calculadora/$', views.Calculadora.as_view(), name='calculadora'),
    url(r'^procesar/$', views.procesar_opcion, name='procesar'),
    url(r'^plan-express/$', views.ProcesarPlanView.as_view(), name='plan-express'),
    url(r'^plan-moderado/$', views.ProcesarPlanView.as_view(), name='plan-moderado'),
    url(r'^plan-largo-plazo/$', views.ProcesarPlanView.as_view(), name='plan-lp'),
    url(r'^tu-cotizacion/$', views.TuCotizacion.as_view(), name='tu-cotizacion'),
]

ecoclientes/urls.py
from django.conf.urls import url

from . import views

app_name = 'ecoclientes'
urlpatterns = [
    url(r'^nuevo-registro/$', views.nuevo_registro, name='nuevo_registro'),
    url(r'^pre-registro/$', views.preregistro, name='pre_registro'),
    url(r'^registrar-equipo/$', views.nuevo_equipo, name='nuevo_equipo'),
    url(r'^ver-registro/(?P<fxf>[^/]+)$', views.ver_registro, name='ver_registro'),
    url(r'^editar/(?P<fxf>[^/]+)$', views.editar_registro, name='editar_registro'),
    url(r'^editar_equipo/(?P<pk>[^/]+)$', views.editar_equipo, name='editar_equipo'),
    url(r'^edita_inventario/(?P<pk>[^/]+)$', views.edita_inventario, name='edita_inventario'),
    url(r'^edita_descuentos/(?P<pk>[^/]+)$', views.editar_descuento, name='editar_descuentos'),
    url(r'^ver-registros/$', views.ver_registros, name='ver_registros'),
    url(r'^ver-registros/(?P<DAR>[^/]+)$', views.ver_registrosdar, name='ver_registrosdar'),
    url(r'^ver-registros-liberados/(?P<fxf>[^/]+)$', views.ver_registros_liberados, name='ver_registros_liberados'),
    url(r'^ver-todo/$', views.ver_todos, name='ver_todo'),
    url(r'^agrega-plaza/$', views.agrega_plaza, name='agrega_plaza'),
    url(r'^agrega-modelo/$', views.agrega_modelo, name='agrega_modelo'),
    url(r'^agrega-modeloe/(?P<pk>[^/]+)$', views.agrega_modeloe, name='agrega_modeloe'),
    url(r'^ver-registro/(?P<fxf>[^/]+)/genera-factura/$', views.facturacion, name='genera_factura'),
  #  url(r'^ver-registro/(?P<fxf>[^/]+)/administra-factura/$', views.admon_facturacion, name='administra_factura'),
    url(r'^ver-registro/(?P<fxf>[^/]+)/cancela-factura/$', views.cancela_factura, name='cancela_factura'),
    url(r'^ver-registro/(?P<fxf>[^/]+)/captura-datos-fiscales/$', views.captura_datos_fiscales, name='captura_datos_fiscales'),
    url(r'^resumen/$', views.resumen_eco, name='resumen'),
    url(r'^flujos/$', views.flujos, name='flujos'),
    url(r'^adeudos/$', views.adeudos, name='adeudos'),
    url(r'^flujos/nuevo-inversionista$', views.nuevo_inversionista, name='nuevo_inversionista'),
    url(r'^flujos/(?P<PRLV>[^/]+)$', views.editar_inversionista, name='inversionista'),
    url(r'^flujos/(?P<PRLV>[^/]+)/archivar$', views.archivar_inversionista, name='archivar_inversionista'),
    url(r'^editar-flujos/(?P<semana>[^/]+)$', views.editar_flujos, name='editar_flujos'),
]

ecoluz/urls.py
# -*- coding: utf-8 -*-
"""ecoluz URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from ecoluzweb import views
from django.conf import settings
from django.conf.urls.static import static
from . import views as vw
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)


urlpatterns = [
    url(r'^eco-v1/', admin.site.urls),
    url(r'^$', views.inicio, name='inicio'),
    url(r'^clientes/', include('clientes.urls')),
    url(r'^usuarios/', include('usuarios.urls'), name='usuarios'),
    url(r'^ecoclientes/', include('ecoclientes.urls'), name='ecoclientes'),
    url(r'^conoce-tu-ahorro/', include('bots.urls'), name='conoce-tu-ahorro'),
    url(r'^proyectos/', views.proyectos, name='proyectos'),
    url(r'^que-es-ecoluz/', views.que_es_ecoluz, name='que-es-ecoluz'),
    url(r'^terminos-y-condiciones', views.terminos_y_condiciones, name='terminos-y-condiciones'),
    url(r'^aviso-de-privacidad', views.aviso_de_privacidad, name='aviso-de-privacidad'),
    url(r'^contacto', views.contacto, name='contacto'),
    url(r'^ingresando', vw.wherenext, name='ingresando'),

    url('^reestablecer-contrasena/$', auth_views.password_reset,
        {
            'template_name': 'clientes/password_reset_form.html',
            'html_email_template_name': 'clientes/password_reset_email.html',
        }, name='password_reset'),
    url(r'^reestablecer-contrasena/listo/$',
        PasswordResetDoneView.as_view(template_name='clientes/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reestablecer-contrasena/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='clientes/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reestablecer-contrasena/hecho/$',
        PasswordResetCompleteView.as_view(template_name='clientes/password_reset_complete.html'),
        name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
)

from . import views
app_name = 'usuarios'
urlpatterns = [
    url(r'^acceso/$', login, {'template_name': 'usuarios/login.html'}, name='acceso'),
    url(r'^adios/$', logout, {'template_name': 'usuarios/logout.html'}, name='adios'),
    url(r'^registro/$', views.registro, name='registro'),
    url(r'^perfil/$', views.perfil, name='perfil'),
    url(r'^perfil/editar/$', views.editar_perfil, name='editar_perfil'),
    url(r'^cambiar-contrasena/$', views.cambiar_contrasena, name='cambiar_contrasena'),
    url(r'^reestablecer-contrasena/$', password_reset, {'template_name': 'usuarios/reestablecer-contrasena.html'},  name='reestablecer-contrasena'),
    url(r'^reestablecer-contrasena/listo/$', password_reset_done, name='password_reset_done'),
    url(r'^reestablecer-contrasena/confirmar/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^reestablecer-contrasena/hecho/$', password_reset_complete, {'template_name': 'usuarios/password_rscmp.html'}, name='password_rscmp'),
]

ecoclientes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext as _
from django.core.validators import RegexValidator
from usuarios.models import Usuario
from datetime import date, time, datetime
from django.db.models import Q

# Create your models here.


def ecocliente_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'ecoclientes/ecocliente_{0}/{1}'.format(instance.id, filename)


class Plaza(models.Model):

    ciudad_choices = (
         ('ACA', 'Acapulco'),
         ('AGU', 'Aguascalientes'),
         ('MET', 'Área Metropolitana'),
         ('CPE', 'Campeche'),
         ('CUN', 'Cancún'),
         ('CJS', 'Cd. Juárez'),
         ('COB', 'Cd. Obregón'),
         ('CVA', 'Cd. Valles'),
         ('CVM', 'Cd. Victoria'),
         ('CUU', 'Chihuahua'),
         ('CHG', 'Chilpancingo'),
         ('CTZ', 'Coatzacoalcos'),
         ('COL', 'Colima'),
         ('CVJ', 'Cuernavaca'),
         ('CUL', 'Culiacán'),
         ('DGO', 'Durango'),
         ('GDL', 'Guadalajara'),
         ('HMO', 'Hermosillo'),
         ('IRA', 'Irapuato'),
         ('GTO', 'León'),
         ('MAZ', 'Mazatlán'),
         ('MID', 'Mérida'),
         ('MXL', 'Mexicali'),
         ('MTY', 'Monterrey'),
         ('MOR', 'Morelia'),
         ('OAX', 'Oaxaca'),
         ('PCA', 'Pachuca'),
         ('PAZ', 'Poza Rica'),
         ('PUE', 'Puebla'),
         ('PVR', 'Puerto Vallarta'),
         ('QRO', 'Querétaro'),
         ('SCX', 'Salina Cruz'),
         ('SAL', 'Saltillo'),
         ('SLP', 'San Luis Potosí'),
         ('TAM', 'Tampico'),
         ('NAY', 'Tepic'),
         ('TIJ', 'Tijuana'),
         ('TLX', 'Tlaxcala'),
         ('TLC', 'Toluca'),
         ('TRC', 'Torreón'),
         ('TGZ', 'Tuxtla Gutiérrez'),
         ('UPN', 'Uruapan'),
         ('VER', 'Veracruz'),
         ('VSA', 'Villahermosa'),
         ('XAL', 'Xalapa'),
         ('ZAM', 'Zamora')
    )

    DAR = models.ForeignKey(Usuario, on_delete=models.CASCADE, ) #  limit_choices_to=Q('DAR_id'!= '') )
    ciudad = models.CharField(_('Ciudad'), choices=ciudad_choices, max_length=25, blank=True, null=True)
    estado = models.CharField(_('Estado'),  max_length=25, blank=True, null=True)
    clave = models.CharField(_('Clave'),  max_length=3, blank=True, null=True)

    def __unicode__(self):
        return getattr(self.DAR, 'DAR_id')+'-'+str(self.ciudad)

    class Meta:
        ordering = ['DAR']








class Eco(models.Model):
    Estatus_CHOICES = (
        ('EN VALIDACIÓN', 'EN VALIDACIÓN'),
        ('PENDIENTE', 'PENDIENTE'),
        ('PAGADO', 'PAGADO'),
        #('TRASPASO', 'TRASPASO'),
        #('CANCELADO SIN FONDEO', 'CANCELADO SIN FONDEO'),
        ('CANCELADO', 'CANCELADO'),
        ('POR FONDEAR', 'POR FONDEAR'),
        #('ADEUDO', 'ADEUDO'),
        #('INVENTARIO', 'INVENTARIO'),
        #('COM DAR Pendiente', 'COM DAR Pendiente'),
        ('COM DAR CxP a hoy', 'COM DAR CxP a hoy'),
        ('LIBERADO', 'LIBERADO')   )

    # DAR_CHOICES = ( # list(set(a).union(b))
    #     ('PRF-IRA', 'PRF-IRA'),
    #     ('PRF-PUE', 'PRF-PUE'),
    #     ('PRF-SLP', 'PRF-SLP'),
    #     ('SOP-DUR', 'SOP-DUR'),
    #     ('SOP-ZAC', 'SOP-ZAC'),
    #     ('GMC-SIN', 'GMC-SIN'),
    #     ('MCM-MTY', 'MCM-MTY'),
    #     ('MCM-SAL', 'MCM-SAL'),
    #     ('JAM-TOL', 'JAM-TOL'),
    #     ('CNG-TAM', 'CNG-TAM'),
    #     ('EMR-NAY', 'EMR-NAY'),
    #     ('MFV-MTY', 'MFV-MTY'),
    #     ('TCU-MER', 'TCU-MER'),
    #     ('FIT-MTY', 'FIT-MTY'),
    #     ('BHA-XAL', 'BHA-XAL'),
    #     ('POM-GTO', 'POM-GTO'),
    #     ('BPC-HGO', 'BPC-HGO'),
    #     ('AVA-MET', 'AVA-MET'),
    #     ('CGL-MET', 'CGL-MET'),
    #     ('VNT-MET', 'VNT-MET'),
    # )

    tipo_venta_CHOICES = (
        ('PAEEEM', 'PAEEEM'),
        ('CONAVI', 'CONAVI'),
        ('ProveCapital', 'ProveCapital'),
        ('Credijusto', 'Credijusto'),
        ('Afirme', 'Afirme'),
        ('Contado', 'Contado'),)


    tecnologia_CHOICES = (
        ('Refrigerción Comercial', 'Refrigerción Comercial'),
        ('Cámaras de Refrigeración', 'Cámaras de Refrigeración'),
        ('Sistemas Fotovoltaicos', 'Sistemas Fotovoltaicos'),
        ('Aires Acondicionados', 'Aires Acondicionados'),
        ('Luminarias', 'Luminarias'),
        ('Calentadores Solares', 'Calentadores Solares'),
        ('Mejora Estructura', 'Mejora Estructura'),
    )

    fxf = models.CharField(_('FxF'), max_length=16, blank=True, null=True)
    DAR = models.CharField(_('DAR') , max_length=7,  blank=True)
    tipo_venta = models.CharField(_('Tipo de venta') , max_length=25, blank=True, choices=tipo_venta_CHOICES)
    numero_credito = models.CharField(_('Número de crédito'), max_length=20, blank=True)
    first_name = models.CharField(_('Nombre') , max_length=45, blank=True)
    last_name = models.CharField(_('Apellido paterno') , max_length=25, blank=True)
    last_last_name = models.CharField(_('Apellido materno') , max_length=25, blank=True)
    rfc = models.CharField(_('RFC') , max_length=25, blank=True)
    nombre_beneficiario = models.CharField(_('Nombre del Beneficiario'), max_length=80, blank=True, null=True)
    estatus = models.CharField(_('Estatus'), max_length=25, choices=Estatus_CHOICES, default='EN VALIDACION', blank=True)
    fecha_pago = models.DateField(_('Fecha de pago'), blank=True, null=True)
    fecha_compra = models.DateField(_('Fecha de compra'), blank=True, null=True )
    factura_ecoluz_n = models.CharField(_('Factura Eco Luz'),  max_length=200, blank=True, null=True)
    factura_ecoluz = models.FileField(_('Factura Eco Luz.xml'), upload_to=ecocliente_directory_path, blank=True, null=True)
    factura_costos_dar_n = models.CharField(_('Factura Costos DAR'),  max_length=200, blank=True, null=True)
    factura_costos_dar = models.FileField(_('Factura Costos DAR.xml'), upload_to=ecocliente_directory_path, blank=True, null=True)
    subtotal_pago = models.CharField(_('Subtotal de pago'), max_length=20, blank=True, null=True)
    cayd_cobrado = models.CharField(_('CAyD'), max_length=15, blank=True, null=True)

    gastos_inst = models.CharField(_('Gastos de instalación'), max_length=20, blank=True, null=True)
    eqp = models.FloatField(_('EQP'), max_length=15, blank=True, null=True)
    reguladores = models.FloatField(_('Instalación'), max_length=15, blank=True, null=True)
    mdm = models.FloatField(_('MDM'), max_length=15, blank=True, null=True)
    com = models.FloatField(_('COM'), max_length=15, blank=True, null=True)
    man = models.FloatField(_('MAN'), max_length=15, blank=True, null=True)

    monitoreo = models.FloatField(_('Sistema de Monitoreo'), max_length=15, blank=True, null=True)
    montaje = models.FloatField(_('Sistema de Montaje'), max_length=15, blank=True, null=True)

    suministro_instalacion = models.FloatField(_('Suministro de Instalación'), max_length=15, blank=True, null=True, default=0.0)
    estructura = models.FloatField(_('Estructura'), max_length=15, blank=True, null=True, default=0.0)
    inversor = models.FloatField(_('Inversor'), max_length=15, blank=True, null=True, default=0.0)
    microinversor = models.FloatField(_('Microinversor'), max_length=15, blank=True, null=True, default=0.0)

    cayd_pagado = models.FloatField(_('CAYD'), max_length=15, blank=True, null=True)

    subtotal_operacion = models.FloatField(_('Subtotal operación'), max_length=10, blank=True, null=True)
    financiamiento = models.FloatField(_('Financiamiento'), max_length=10, blank=True, null=True)
    costo_total_financiamiento = models.FloatField(_('Costo total financiamiento'), max_length=15, blank=True, null=True)
    pago_total = models.FloatField(_('Pago total'), max_length=15, blank=True, null=True)
    numero_dias = models.IntegerField(_('# Dias'), blank=True, null=True)
    com_dar = models.FloatField(_('COM DAR'), max_length=15, blank=True, null=True)
    adeudos = models.FloatField(_('Adeudos'), max_length=15, blank=True, null=True)
    descuento_f = models.FloatField(_('Descuentos'), max_length=15, default=0, blank=True, null=True)
    obs = models.TextField(_('Observaciones'), max_length=600, blank=True)
    fecha_mod = models.DateField(_('Última modificación'), auto_now=True, null=True)
    # Domicilio
    email = models.CharField('Correo electrónico', blank=True, null=True, max_length=50, default='NOHAY@valor.mx')
    telefono = models.CharField(_('Teléfono'), max_length=12, blank=True, null=True, default='AÑADIR')
    calle = models.CharField(_('Calle'), max_length=50, blank=True, null=True, default='AÑADIR VALOR')
    numero_exterior = models.CharField(_('Número exterior'), max_length=10, blank=True, null=True, default='AÑADIR')
    numero_interior = models.CharField(_('Número interior'), max_length=10, blank=True, null=True, default='AÑADIR')
    colonia = models.CharField(_('Colonia'), max_length=50, blank=True, null=True, default='AÑADIR VALOR')
    delegacion_municipio = models.CharField(_('Delegación o Municipio'), max_length=50, blank=True, null=True, default='AÑADIR VALOR')
    estado = models.CharField(_('Estado'), max_length=50, blank=True, null=True, default='AÑADIR VALOR')
    codigo_postal = models.IntegerField(_('Código postal'), blank=True, null=True, default=0)
    pais = models.CharField(_('País'), blank=True, null=True, max_length=20, default='MX')
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    tecnologia = models.CharField(_('Tecnología'), max_length=50, blank=True, null=True, choices=tecnologia_CHOICES)
    solar = models.BooleanField(_('Solar'), default=0)


    def __unicode__(self):
        return str(self.fxf)

    class Meta:
        ordering = ['fxf']


class Inventario(models.Model):
    modelo = models.CharField(_('Modelo de equipo'), max_length=80, blank=True, null=True)

ecoclientes/templates/ecoclientes/nuevo_equipo.html
{% extends 'ecoclientes/base-eco.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}Nuevo equipo{% endblock %}

    {% block content %}
     <div class="container">
        <div class="row">
            <div class="col-sm-12" style="margin-top: 100px">
                    <div class="col-sm-12" style="background-color: #e5e5e5;">
                        <br>
                            <div class="form-group">
                                <div class="row">
                                <div class="container">
                                <div class="col-md-6 col-md-offset-3 ">
                                    <br><h2>NUEVO EQUIPO</h2>
                                    <br><strong class="strong-green">Registra o completa la información de un Equipo.</strong>
                                <br>
                                    <form method="post" enctype="multipart/form-data" action="{% url 'ecoclientes:nuevo_equipo' %}">
                                        {% csrf_token %}
                                        {{ nvo_equipo | crispy  }}
                                        <p align="right">
                                        <input type="hidden" name="next" value="{{ request.path }}">
                                        <a style="background:white;" href="{% url 'ecoclientes:agrega_modelo'  %}" class="btn btn-primary">Agregar un nuevo modelo de equipo</a>
                                        &nbsp;</p>
                                        <button type="submit" name="registrar_otro" class="btn btn-flat btn-primary">Registrar otro equipo</button>
                                        <button type="submit" name="enviar" class="btn btn-flat btn-primary">GUARDAR</button>
                                            {% for error in field.errors %}
                                              <p style="color: red">{{ error }}</p>
                                            {% endfor %}
                                          </p>
                                      </form>
                                    </div>
                                </div>
                                </div>
                            </div>
                        <br> </div>
                    <br> </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br>
    <!--<script type="text/javascript" src="{% static 'js/plazasDAR.js' %}"></script>-->


</div>

    {% endblock %}
    <!-- End container -->
    <!-- Start footer -->
    {% block footer %}
    {% include 'footer/_footer-sections.html' %}
    {% include 'TYC_modal.html' %}
    {% endblock %}
    <!-- End footer -->
    {% block js-special %}
    <script type="text/javascript" src="{% static 'js/tyc.js' %}"></script>
    {% endblock %}

ecoclientes/templates/ecoclientes/preregistro.html
{% extends 'ecoclientes/base-eco.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}Nuevo registro{% endblock %}

    {% block content %}
     <div class="container">
        <div class="row">
            <div class="col-sm-12" style="margin-top: 100px">
                    <div class="col-sm-12" style="background-color: #e5e5e5;">
                        <br>
                            <div class="form-group">
                                <div class="row">
                                <div class="container">
                                <div class="col-md-6 col-md-offset-3 ">
                                    <br><h2>NUEVO REGISTRO</h2>
                                    <br><strong class="strong-green">Ingresa un nuevo registro al ECO.</strong>
                                <br>

                                    {% if messages %}
                                    <div class="row">
                                            <div class="col-md-2"></div>
                                     <div class="alert alert-danger col-md-6">
                                        <ul>
                                            {% for message in messages %}
                                            <li>{{ message }}</li>
                                            {% endfor %}
                                        </ul>
                                     </div>
                                     </div>
                                    {% endif %}
                                    <form method="post" enctype="multipart/form-data" >
                                    <!--<form method="post" enctype="multipart/form-data">-->
                                        {% csrf_token %}
                                        {{ prereg | crispy  }}
                                        <button type="submit" class="btn btn-flat btn-primary" id="consultar">SIGUIENTE</button>
                                        <a href="{% url 'ecoclientes:agrega_plaza'  %}" class="btn btn-flat btn-primary">Agregar nueva plaza</a>
                                        <a href="{% url 'usuarios:registro'  %}" class="btn btn-flat btn-primary">Agregar nuevo DAR</a>
                                        <div class="row">
                                                <br>
                                                <p class="col-md-4 col-md-offset-3" id="espere" style="display:none; width: 40% !important;">Obteniendo información desde FIDE...</p>
                                                <div class="col-md-2 col-md-offset-4"></div><img src="{% static 'images/loadingfide.gif' %}" id="img" style="display:none; width: 90px;" />
                                        </div>
                                            {% for error in field.errors %}
                                              <p style="color: red">{{ error }}</p>
                                            {% endfor %}
                                          </p>
                                      </form>
                                    </div>
                                </div>
                                </div>
                            </div>
                        <br> </div>
                    <br> </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br>
    <!--<script type="text/javascript" src="{% static 'js/plazasDAR.js' %}"></script>-->


</div>

    {% endblock %}
    <!-- End container -->
    <!-- Start footer -->
    {% block footer %}
    {% include 'footer/_footer-sections.html' %}
    {% include 'TYC_modal.html' %}
    {% endblock %}
    <!-- End footer -->
    {% block js-special %}
    <script type="text/javascript" src="{% static 'js/tyc.js' %}"></script>
    <script>
         $('#consultar').click(function(){
                var opt = $("#id_tipo_venta>option:selected").html()
                console.log(opt);
                console.log(document.getElementById("id_numero_credito").checkValidity());
                console.log(document.getElementById("id_DAR").checkValidity());
                console.log(opt == "PAEEEM")
                if( opt == "PAEEEM" && document.getElementById("id_numero_credito").checkValidity() && document.getElementById("id_DAR").checkValidity() ) {
                $('#img').show(); //<----here
                document.getElementById("espere").style.display = "block";
            }
        });
    </script>
    {% endblock %}